### ISSUE TITLE
Version after 5.9.8

### ISSUE THREAD

**Issue by Vages** [sezna/nps#212]
Hi! I'm hoping the next version (containing 8acd82f141d73e40ef45f6790d85f3a1b9923302 which fixes the `mem` vulnerability) will be out soon. 

I understand that there is probably some good reasons (personal or technical) that it's being held up. And if it's a technical thing, I'd be glad to help.

PS: Thanks for maintaining a great package. It's probably my number one recommendation these days. Are you going to set up some donate button?

**Comment by sezna** [comment]
I will go ahead and  set up a deploy for tonight or tomorrow. I was dragging my feet a little, anticipating something else to get submitted, but I don't think that is happening soon. 

As for the donate button, this package was originally created by @kentcdodds. I took it over because he didn't have the resources to maintain it in addition to all of his other big projects. I'd recommend using Github's "Sponsor" feature on his profile. 

I will close this issue when I do the deploy.

**Comment by sezna** [comment]
@Vages https://www.npmjs.com/package/nps done.
